apiVersion: v1
kind: Service
metadata:
  name: aiservice
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: aiservice
  ports:
    - port: 3004
      targetPort: 3004
  type: LoadBalancer